apiVersion: v1
kind: Service
metadata:
  name: mailserver
  namespace: mail
spec:
  type: ClusterIP
  selector:
    app: mailserver
  ports:
    - port: 25
      targetPort: 25
      protocol: TCP
      name: smtp
    - port: 587
      targetPort: 587
      protocol: TCP
      name: submission
    - port: 993
      targetPort: 993
      protocol: TCP
      name: imaps
