apiVersion: apps/v1
kind: Deployment
metadata:
  name: rainloop
  namespace: mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rainloop
  template:
    metadata:
      labels:
        app: rainloop
    spec:
      containers:
        - name: rainloop
          image: hardware/rainloop
          ports:
            - containerPort: 80
          volumeMounts:
            - name: rainloop-data
              mountPath: /rainloop/data
      volumes:
        - name: rainloop-data
          persistentVolumeClaim:
            claimName: rainloop-data
