apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-godaddy
spec:
  acme:
    email: YOUR_EMAIL
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-godaddy-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.mycompany.com
            solverName: godaddy
            config:
              apiKeySecretRef:
                name: godaddy-api-secret
                key: GODADDY_API_KEY
              apiSecretSecretRef:
                name: godaddy-api-secret
                key: GODADDY_API_SECRET