apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-godaddy
spec:
  acme:
    email: YOUR_EMAIL  # ⛔請改成你真的 email，Let's Encrypt 會發通知
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-godaddy-key  # ⛔ 沒建立的話會自動生成，確認無誤即可
    solvers:
      - dns01:
          webhook:
            groupName: acme.foson.co
            solverName: godaddy
            config:
              apiKeySecretRef:
                name: godaddy-api-secret
                key: GODADDY_API_KEY
              apiSecretSecretRef:
                name: godaddy-api-secret
                key: GODADDY_API_SECRET
