apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http
  namespace: mail
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@foson.co
    privateKeySecretRef:
      name: letsencrypt-http-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
