apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mariadb-pvc.yaml
  - mariadb-service.yaml
  - mariadb-statefulset.yaml
  - postfixadmin-pvc.yaml
  - postfixadmin-config.yaml
  - postfixadmin-deployment.yaml
  - postfixadmin-service.yaml
  - ingress.yaml