# mail/postfixadmin.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postfixadmin-config
  labels:
    app: postfixadmin

data:
  config.local.php: |
    <?php
    $CONF['setup_password'] = '$2y$10$YAbSszIOoP8dpsynrM1rKeWGPZuz20YEg/dRh33iLhlUPSLMBO9IO';
    $CONF['default_language'] = 'en';
    $CONF['database_type'] = 'mysqli';
    $CONF['database_host'] = 'mariadb';
    $CONF['database_user'] = 'mailuser';
    $CONF['database_password'] = 'mailpass';
    $CONF['database_name'] = 'mailserver';

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfixadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfixadmin
  template:
    metadata:
      labels:
        app: postfixadmin
    spec:
      containers:
      - name: postfixadmin
        image: postfixadmin:3.3
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /var/www/html/config.local.php
          subPath: config.local.php
      volumes:
      - name: config-volume
        configMap:
          name: postfixadmin-config

---
apiVersion: v1
kind: Service
metadata:
  name: postfixadmin
spec:
  selector:
    app: postfixadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

