apiVersion: apps/v1
kind: Deployment
metadata:
  name: rainloop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rainloop
  template:
    metadata:
      labels:
        app: rainloop
    spec:
      containers:
      - name: rainloop
        image: hardware/rainloop
        ports:
        - containerPort: 80
